<?php

namespace AppBundle\Repository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAlbumsFor($genre) {
		
		$query = $this->getEntityManager()
					->createQuery(
						'SELECT a, g FROM AppBundle:Album a
						JOIN a.genre g 
						WHERE g.name = :name
						'
					)->setParameter('name', $genre);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

	public function getAlbumsWithArtists() {

		return $this->getEntityManager()
					->createQuery(
						'SELECT a, artist FROM AppBundle:Album a
						LEFT JOIN a.artist artist
						'
					)->getResult();
	}
}
