<?php

namespace AppBundle\Repository;

/**
 * DoctrineORMGenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineORMGenreRepository extends \Doctrine\ORM\EntityRepository implements GenreInterface
{
	public function getGenresWithAlbums() {
		
		$qb = $this->getEntityManager()->createQueryBuilder();

		return $qb->select(array('g', 'a'))
					->from('AppBundle\Entity\Genre', 'g')
					->leftJoin('g.albums', 'a')
					->getQuery()
					->getResult();
	}

	public function all() {
		return $this->findAll();
	}

}
