<?php

namespace AppBundle\Repository;

use Symfony\Component\Security\Core\User\UserInterface as CoreUserInterface;
use AppBundle\Entity\Order;
use AppBundle\Entity\Orderdetail;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineORMOrderRepository extends \Doctrine\ORM\EntityRepository implements OrderInterface {

	/**
	 * @param array $items
	 * @param float $total
	 * @param CoreUserInterface $user
	 *
	 * @return boolean
	 */
	public function process(array $items, $total, CoreUserInterface $user) {		

		try {
			$order = new Order();
			$order->setTotal($total);
			$order->setUser($user);
			$this->getEntityManager()->persist($order);

			$albumRepository = $this->getEntityManager()->getRepository('AppBundle:Album');
			$albums = $albumRepository->findById(array_keys($items));
			
			foreach($items as $album_id => $item) {
				$orderdetail = new Orderdetail();
				$orderdetail->setQuantity($item['qty']);
				$orderdetail->setPrice($item['entity']['price']);
				$orderdetail->setOrder($order);
				$orderdetail->setAlbum($albumRepository->findOneById($album_id));
				$this->getEntityManager()->persist($orderdetail);
			}

			$this->getEntityManager()->flush();			
			
		} catch (\Exception $e) {			
			return false;
		}
		return true;		

	}

}
