<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Album;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineORMAlbumRepository extends \Doctrine\ORM\EntityRepository implements AlbumInterface
{
	public function getAlbumsFor($genre) {
		
		$query = $this->getEntityManager()
					->createQuery(
						'SELECT a, g FROM AppBundle:Album a
						JOIN a.genre g 
						WHERE g.name = :name
						'
					)->setParameter('name', $genre);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

	public function getAlbumsWithArtistsAndOrders() {

		return $this->getEntityManager()
					->createQuery(
						'SELECT a, artist, od FROM AppBundle:Album a
						LEFT JOIN a.artist artist
						LEFT JOIN a.orderdetails od
						'
					)->getResult();
	}

	public function getById($id) {

		return $this->find($id);

	}

	public function save(Album $album, $insert = true) {
		if ($insert) {
			$this->getEntityManager()->persist($album);	
		}		
		$this->getEntityManager()->flush();
	}

	public function delete(Album $album) {
		$this->getEntityManager()->remove($album);
		$this->getEntityManager()->flush();
	}

	public function newEntity() {
		return new Album;
	}
}
