<?php

namespace AppBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAlbumsFor($genre) {
		
		$query = $this->getEntityManager()
					->createQuery(
						'SELECT a, g FROM AppBundle:Genre g
						JOIN a.genre g 
						WHERE g.name = :name
						'
					)->setParameter('name', $genre);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

}
