<?php

namespace AppBundle\Repository;

/**
 * OrderdetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderdetailRepository extends \Doctrine\ORM\EntityRepository
{
}
