# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.session_storage:
        class: AppBundle\Storage\SessionStorage 
        arguments: ['@session']

    app.cart:
        class: AppBundle\Cart\Cart 
        arguments: ['@app.session_storage']
    
    
    # define entity repositories as services in order to be injected into controllers
    app.doctrine_genre_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Genre  
        autowiring_types: AppBundle\Repository\GenreInterface

    app.doctrine_album_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Album 
        autowiring_types: AppBundle\Repository\AlbumInterface

    app.doctrine_user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User 
        autowiring_types: AppBundle\Repository\UserInterface


    # define controller as a service
    app.store_controller:
        class: AppBundle\Controller\StoreController
        autowire: true

    app.admin.store_controller:
        class: AppBundle\Controller\Admin\StoreController 
        autowire: true

    app.shopping_controller:
        class: AppBundle\Controller\ShoppingController 
        autowire: true
        calls:
            - [ setContainer, ['@service_container']]
        
        
    # services to be injected in the controllers defined as a service
    app.common_services:
        class: AppBundle\Services\CommonServices 
        arguments: ['@templating', '@router', '@form.factory', '@session']
    
    # authentication services
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator 
        autowire: true
        calls:
            - [ setRouter, ['@router']]

    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator 
        arguments: ['@security.password_encoder', '@router', '@security.csrf.token_manager']
